// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtpirrtjzhbddwpwgazq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cGlycnRqemhiZGR3cHdnYXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTQ3NDYsImV4cCI6MjA2ODYzMDc0Nn0.GSlkjyYbF5aiNGSTFIKIvcBgow5kRviWUF8KILSmK-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});